# Generated by Django 4.2.27 on 2026-01-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_video_consultation',
            field=models.BooleanField(default=False, help_text='Whether this is a video consultation'),
        ),
    ]
