# Generated by Django 4.2.27 on 2026-01-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_is_video_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='pending', help_text='Payment status: pending, paid, refunded', max_length=20),
        ),
    ]
