# Generated by Django 4.2.27 on 2026-01-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_payment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_slot',
        ),
    ]
